name: Bash Script Tests

on: [push, pull_request]

jobs:
  bash-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install shunit2
        run: sudo apt-get update && sudo apt-get install -y shunit2

      - name: Run Shell Tests
        run: |
          cd tests
          chmod +x *.sh
          bash sample_test.sh
